import { put, del, list } from '@vercel/blob';

export const STORAGE_BUCKETS = ['images','videos','audio','documents','generated','uploads'] as const;
export type StorageBucket = (typeof STORAGE_BUCKETS)[number];
export function isStorageConfigured() { return Boolean(process.env.BLOB_READ_WRITE_TOKEN); }
export function buildStoragePath(userId: string, filename: string, folder?: string) { const safe = filename.replace(/[^a-zA-Z0-9._\-\u0600-\u06FF]/g, '_').slice(0, 80); const id = `${Date.now()}_${Math.random().toString(36).slice(2,8)}`; return `${userId}/${folder ? `${folder}/` : ''}${id}_${safe}`; }
export async function uploadToBucket(opts: { bucket: StorageBucket; path: string; data: Buffer | Blob | ArrayBuffer; contentType?: string; upsert?: boolean }) { try { const body = opts.data instanceof ArrayBuffer ? Buffer.from(opts.data) : opts.data; const blob = await put(`${opts.bucket}/${opts.path}`, body as any, { access: 'public', contentType: opts.contentType || 'application/octet-stream', addRandomSuffix: false, allowOverwrite: opts.upsert ?? false }); return { path: opts.path, publicUrl: blob.url }; } catch (error: any) { return { path: opts.path, publicUrl: null, error: error?.message || 'فشل رفع الملف' }; } }
export async function removeFromBucket(bucket: StorageBucket, path: string) { try { await del(`${bucket}/${path}`); return { error: undefined }; } catch (error: any) { return { error: error?.message }; } }
export async function listUserFiles(bucket: StorageBucket, userId: string, limit = 50) { try { const result = await list({ prefix: `${bucket}/${userId}/`, limit }); return { files: result.blobs.map(blob => ({ name: blob.pathname.split('/').pop(), path: blob.pathname.replace(`${bucket}/`, ''), size: blob.size, updatedAt: blob.uploadedAt, publicUrl: blob.url })), error: null }; } catch (error: any) { return { files: [], error: error?.message || 'تعذر قراءة الملفات' }; } }
