#!/usr/bin/env python3
"""Migrate public-schema data from a Supabase plain SQL dump into Neon.

The script deliberately does not import Supabase roles, auth, storage, realtime,
GraphQL, vault, extensions, policies, or functions. Create the target schema with
Prisma first, then run this script against the empty Neon database.

Safe default: dry-run only. Actual writes require --apply and NEON_DATABASE_URL.
"""
from __future__ import annotations

import argparse
import gzip
import os
import re
import subprocess
import sys
import tempfile
from collections import OrderedDict
from pathlib import Path

# Parent tables first; this order satisfies the foreign keys in this project.
TABLE_ORDER = [
    'User',
    'Plan',
    'AiProvider',
    'ServiceCost',
    'Setting',
    'Profile',
    'AiModel',
    'ProviderKey',
    'Subscription',
    'Wallet',
    'WalletTransaction',
    'AiJob',
    'GeneratedFile',
    'Payment',
    'GiftCode',
    'SystemLog',
    'ApiRequest',
    'AiUsageLog',
    'WithdrawRequest',
]

COPY_RE = re.compile(r'^COPY public\.([A-Za-z0-9_" ]+) \((.*)\) FROM stdin;$')


def read_dump(path: Path) -> list[str]:
    if not path.exists():
        raise SystemExit(f'لا يوجد ملف dump: {path}')
    if path.suffix == '.gz' or path.name.endswith('.backup.gz'):
        with gzip.open(path, 'rt', encoding='utf-8', errors='strict', newline='') as fh:
            return fh.read().splitlines()
    return path.read_text(encoding='utf-8', errors='strict').splitlines()


def parse_public_copy(lines: list[str]) -> OrderedDict[str, tuple[str, list[str]]]:
    """Return table -> (COPY header, raw data lines), preserving dump escaping."""
    blocks: OrderedDict[str, tuple[str, list[str]]] = OrderedDict()
    i = 0
    while i < len(lines):
        match = COPY_RE.match(lines[i])
        if not match:
            i += 1
            continue
        table = match.group(1)
        header = lines[i]
        data: list[str] = []
        i += 1
        while i < len(lines) and lines[i] != r'\.':
            data.append(lines[i])
            i += 1
        if i == len(lines):
            raise ValueError(f'قسم COPY غير مكتمل للجدول public."{table}"')
        blocks[table] = (header, data)
        i += 1
    return blocks


def normalize_table(name: str) -> str:
    return name.strip('"')


def ordered_blocks(blocks: OrderedDict[str, tuple[str, list[str]]]):
    known = {normalize_table(k): k for k in blocks}
    ordered: list[str] = []
    for wanted in TABLE_ORDER:
        if wanted in known:
            ordered.append(known[wanted])
    for original in blocks:
        if original not in ordered:
            ordered.append(original)
    return ordered


def sql_identifier(name: str) -> str:
    return 'public."' + name.replace('"', '""') + '"'


def make_sql(blocks: OrderedDict[str, tuple[str, list[str]]], *, empty_only: bool) -> str:
    out = [
        '-- Generated by migrate_supabase_public.py',
        '-- Only public-schema COPY data is included; no Supabase internals are imported.',
        'BEGIN;',
        'SET lock_timeout = \'30s\';',
        'SET statement_timeout = \'10min\';',
        '',
    ]
    if empty_only:
        out += [
            '-- Abort if the target is not empty. This prevents accidental duplicate imports.',
            "DO $$ DECLARE r record; n bigint; BEGIN",
            "  FOR r IN SELECT table_name FROM information_schema.tables WHERE table_schema='public' AND table_type='BASE TABLE' LOOP",
            "    EXECUTE format('SELECT count(*) FROM public.%I', r.table_name) INTO n;",
            "    IF n > 0 THEN RAISE EXCEPTION 'Target table public.% contains data; aborting', r.table_name; END IF;",
            "  END LOOP;",
            'END $$;',
            '',
        ]
    for table in ordered_blocks(blocks):
        header, data = blocks[table]
        out.append(f'-- {table}: {len(data)} rows')
        out.append(header)
        out.extend(data)
        out.append(r'\.')
        out.append('')
    out += [
        '-- Counts are checked by the caller after commit.',
        'COMMIT;',
        '',
    ]
    return '\n'.join(out)


def table_counts_sql(blocks: OrderedDict[str, tuple[str, list[str]]]) -> str:
    statements = []
    for table in ordered_blocks(blocks):
        statements.append(f'SELECT {sql_identifier(normalize_table(table))!r} AS table_name, count(*) AS rows FROM {sql_identifier(normalize_table(table))};')
    return '\n'.join(statements) + '\n'


def run_psql(database_url: str, sql_file: Path) -> int:
    command = ['psql', database_url, '--set', 'ON_ERROR_STOP=1', '--file', str(sql_file)]
    print('تشغيل psql على Neon...')
    return subprocess.run(command, check=False).returncode


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('dump', type=Path, help='مسار db_cluster...backup.gz')
    parser.add_argument('--export-sql', type=Path, help='حفظ SQL public المنقى في هذا المسار')
    parser.add_argument('--apply', action='store_true', help='تنفيذ الكتابة فعلياً إلى NEON_DATABASE_URL')
    parser.add_argument('--allow-non-empty', action='store_true', help='عدم فحص أن جداول Neon فارغة (غير موصى به)')
    args = parser.parse_args()

    lines = read_dump(args.dump)
    blocks = parse_public_copy(lines)
    if not blocks:
        raise SystemExit('لم يتم العثور على أي COPY من public في النسخة.')

    print(f'تم العثور على {len(blocks)} جدولاً في public.')
    total = 0
    for table in ordered_blocks(blocks):
        count = len(blocks[table][1])
        total += count
        print(f'  public."{normalize_table(table)}": {count} سجل')
    print(f'الإجمالي: {total} سجل')

    sql = make_sql(blocks, empty_only=not args.allow_non_empty)
    export_path = args.export_sql
    temporary = None
    if export_path:
        export_path.parent.mkdir(parents=True, exist_ok=True)
        export_path.write_text(sql, encoding='utf-8', newline='\n')
        print(f'تم حفظ SQL المنقى في: {export_path}')
    else:
        temporary = tempfile.NamedTemporaryFile('w', suffix='.sql', delete=False, encoding='utf-8', newline='\n')
        temporary.write(sql)
        temporary.close()
        export_path = Path(temporary.name)

    if not args.apply:
        print('DRY-RUN فقط: لم يتم الاتصال بـ Neon ولم تُكتب أي بيانات.')
        print('للتنفيذ: export NEON_DATABASE_URL=... ثم أعد الأمر مع --apply')
        if temporary:
            export_path.unlink(missing_ok=True)
        return 0

    database_url = os.environ.get('NEON_DATABASE_URL', '').strip()
    if not database_url:
        raise SystemExit('يلزم ضبط NEON_DATABASE_URL عند استخدام --apply.')
    if not database_url.startswith(('postgres://', 'postgresql://')):
        raise SystemExit('NEON_DATABASE_URL يجب أن يكون رابط PostgreSQL صحيحاً.')

    try:
        return run_psql(database_url, export_path)
    finally:
        if temporary:
            export_path.unlink(missing_ok=True)


if __name__ == '__main__':
    sys.exit(main())
